server:
  port: 8081
  max-http-header-size: 2621440

spring:
  profiles:
    active: dev
  banner:
    location: banner.txt
  datasource:
    username: root
    password: Qq1196726420!
    url: jdbc:mysql://localhost:3306/brahman?ServerTimeZone=UTC-4&CharacterEncoding=utf-8&UseUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 12
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    username: katamina234@gmail.com
    password: ibivgielqqwibtvm
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath:mybatis/mapper/*.xml
  #  type-aliases-package: com.ntr.entity
